---
ID: "b139deae-a676-4616-8dcc-82be3568cd75"
Parent: "e9812f00-c6c5-4d66-9beb-70acd9e3cf2b"
Template: "e9812f00-c6c5-4d66-9beb-70acd9e3cf2b"
Path: /sitecore/templates/Project/Company DEV/Partial Designs/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {D66F5C1B-4DCC-4FD2-950A-1695F6A1D85D}
    {FD2059FD-6043-4DFE-8C04-E2437CE87634}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240830T093715Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\anthony.scrimali@cgi.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\anthony.scrimali@cgi.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "92b082a7-11e0-4002-a2ed-19741ce6a41b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\anthony.scrimali@cgi.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240830T093719Z
